using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interactivity;

namespace WpfMailSender.Behaviours
{
    public class BindingStyleForAutoGenerateColumnsBehaviour : Behavior<DataGrid>
    {
        protected override void OnAttached()
        {
            AssociatedObject.AutoGeneratedColumns += OnAutoGeneratedColumns;
        }

        protected override void OnDetaching()
        {
            AssociatedObject.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        }

        public static void OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            if (sender is DataGrid dataGrid)
            {
                foreach (var column in dataGrid.Columns)
                {
                    var propertyInfoStyleList = column.GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.Public).Where(p => p.Name.EndsWith("Style"));

                    var stylesForProperties = propertyInfoStyleList
                        .Select(p => (PropertyInfo: p, Style: (Style)dataGrid.TryFindResource(string.Concat(column.GetType().Name, ".", p.Name))))
                        .ToList();

                    foreach (var propertyStylePair in stylesForProperties)
                    {
                        if (propertyStylePair.Style != null)
                        {
                            propertyStylePair.PropertyInfo.SetValue(column, propertyStylePair.Style);
                        }
                    }
                }
            }
        }
    }
}
